ctf/urls.py
from django.urls import path
from . import views

app_name='ctf'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
    path('leaderboard/', views.Leaderboard.as_view(), name='leaderboard'),
    path('submit-flag/', views.submit_flag, name='submit-flag'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

handler404 = 'ctf.views.handle404'
handler500 = 'ctf.views.handle500'

ethihack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ctf/', include('ctf.urls')),
    path('', lambda x : redirect('ctf:home', permanent=True)),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ctf/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

CITIES = [
    ("Diana","Diana"),
    ("Sava","Sava"),
    ("Itasy","Itasy"),
    ("Analamanga","Analamanga"),
    ("Vakinankaratra","Vakinankaratra"),
    ("Bongolava","Bongolava"),
    ("Sofia","Sofia"),
    ("Boeny","Boeny"),
    ("Betsiboka","Betsiboka"),
    ("Melaky","Melaky"),
    ("Alaotra-Mangoro","Alaotra-Mangoro"),
    ("Atsinanana","Atsinanana"),
    ("Analanjirofo","Analanjirofo"),
    ("Amoron'i Mania","Amoron'i Mania"),
    ("Vatovavy","Vatovavy"),
    ("Haute Matsiatra","Haute Matsiatra"),
    ("Fitovinany","Fitovinany"),
    ("Atsimo-Atsinanana","Atsimo-Atsinanana"),
    ("Ihorombe","Ihorombe"),
    ("Menabe","Menabe"),
    ("Atsimo-Andrefana","Atsimo-Andrefana"),
    ("Androy","Androy"),
    ("Anôsy","Anôsy"),
]

class Flag(models.Model):
    value = models.CharField(max_length=100)
    description = models.TextField()

class Hint(models.Model):
    flag = models.ForeignKey(Flag, on_delete=models.CASCADE)
    value = models.CharField(max_length=200)
    
class Team(models.Model):
    profile = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=100, choices=CITIES)
    last_flag_found = models.DateTimeField(null=True, blank=True)
    flag_found = models.ManyToManyField(Flag, related_name='flag_found', blank=True)
    current_flag = models.ForeignKey(Flag, on_delete=models.SET_NULL, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.current_flag:
            self.current_flag = Flag.objects.first()
        if self.id and self.flag_found.count() and not self.last_flag_found:
            self.last_flag_found = timezone.now()
        return super(Team,self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name

    def found_flag(self):
        if self.current_flag:
            self.flag_found.set([*self.flag_found.all(), self.current_flag], clear=False)
            self.current_flag = Flag.objects.get(pk = self.current_flag.id + 1)
            self.last_flag_found = timezone.now()
            self.save()

    def flag_validated(self):
        return self.flag_found.count()

ctf/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Team
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.db import models


def home(request):
    return render(request, 'ctf/home.html')

def about(request):
    return render(request, 'ctf/about.html')

def rules(request):
    return render(request, 'ctf/rules.html')

@login_required
def submit_flag(request):
    team = Team.objects.get(profile = request.user.id)
    if request.method =='POST':
        flag_value = request.POST.get('flag')
        if flag_value and team.current_flag.value == flag_value:
            team.found_flag()
            
    context = {
        'team': team
    }
    return render(request, 'ctf/submit-flag.html', context)


class Leaderboard(ListView):
    model = Team
    template_name = 'ctf/leaderboard.html'
    def get_context_data(self, **kwargs):        
        all_teams = Team.objects.all().annotate(count_flag_found=models.Count('flag_found')).order_by('-count_flag_found','last_flag_found')
        top_teams = all_teams.exclude(last_flag_found__isnull=True)[:18]
        teams =  all_teams.exclude(pk__in=top_teams.values_list('pk', flat=True))
        context = {
            'top_teams': top_teams,
            'teams': teams
        }
        return context
    

class UserLoginView(LoginView):
    template_name = 'ctf/login.html'
    success_url = reverse_lazy('ctf:home')
    redirect_authenticated_user = True
    
class UserLogoutView(LogoutView):
    pass

# Errors : 
def handle404(request, exception=None):
    return render(request, '404.html', {})


def handle500(request, exception=None):
    return render(request, '500.html', {})

templates/container.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}{% endblock title %}
        </title>
        {% comment %} font awesome bootstrap {% endcomment %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        {% comment %} bootstrap {% endcomment %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        {% block styles %}{% endblock styles %}
            
    </head>
    <body class="bg-dark">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between px-3 py-2 mb-4 border-bottom bg-secondary">
            <a href="{% url 'ctf:home' %}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                <img src="{% static 'images/logo-header.jpg' %}" alt="Logo ethihack header" height="50">
                <strong class="text-white">ETHIHACK</strong>
            </a>
        
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'ctf:home' %}" class="nav-link px-2 link-warning">Home</a></li>
                <li><a href="{% url 'ctf:about' %}" class="nav-link px-2 link-light">About</a></li>
                <li><a href="{% url 'ctf:leaderboard' %}" class="nav-link px-2 text-white">Leaderboard</a></li>
                <li><a href="{% url 'ctf:rules' %}" class="nav-link px-2 link-light">Rules</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'ctf:submit-flag' %}" class="nav-link px-2 link-light">Submit flag</a></li>
                {% endif %}
            </ul>
            
            <div class="col-md-3 text-end">
                {% if not user.is_authenticated %}
                    <a href="{% url 'ctf:login' %}" class="btn btn-outline-light me-2">Login</a>
                {% else %}
                    <span class="text-white">{{user.username}}</span>
                    <a href="{% url 'ctf:logout' %}" class="btn btn-outline-light me-2">Logout</a>
                {% endif %}
            </div>    
        </header>
        {% block content %}{% endblock content %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        
        {% block scripts %}{% endblock scripts %}
    </body>
</html>

templates/ctf/about.html
{% extends 'container.html' %}

{% block content %}
    <h4 class="text-white">Hello there,</h4>
    <p class="text-white">I am waiting for <b>YOUR</b> innovating new ideas</p>
{% endblock content %}
    

templates/ctf/home.html
{% extends 'container.html' %}

{% block content %}
    <p class="text-white">Hello everyone</p>
    <h3 class="text-white">Welcome to <b class="h1 title">ETHIHACK</b></h3>
{% endblock content %}
    

templates/ctf/leaderboard.html
{% extends 'container.html' %}

{% block content %}
    <h1 class="title h1 text-white text-center">Leaderboard</h1>

    <div class="container">
        {% for team in top_teams %}
            {% if forloop.first %}
                <div class="my-3">
                    <div class="d-flex flex-row justify-content-start align-items-center">        
            {% endif %}
            
            {% if team.profile == user %}
                <div class="bg-warning p-2 col-4 border border-secondary rounded">
                
            {% else %}
                <div class="bg-light p-2 col-4 border border-secondary rounded">
                
            {% endif %}
                
                <div class="row">
                    <div class="col-10">
                        <h5 style="width: 100%;">{{team.name}}</h5>
                        <p>From : {{team.city}}</p>
                    </div>
                    <div class="col-2 text-success">{{forloop.counter}}</div>
                </div>
                <div class="d-flex flex-row align-items-center justify-content-around">
                    <div>
                        <small class="text-center">Flag validated : </small>
                        <p class="text-center" >{{ team.flag_validated }}</p>
                    </div>
                    <div>
                        <small class="text-center">Last flag found : </small>
                        <p class="text-center">{{ team.last_flag_found }}</p>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:3 %}
                    </div>
                </div>
                <div class="my-3">
                    <div class="d-flex flex-row justify-content-start align-items-center">        
            {% endif %}
            {% if forloop.last %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        {% for team in teams %}
            <div class="d-flex flex-row my-2 bg-dark">
                    
                    {% if team.profile == user %}
                        <div class="col-1 d-flex bg-danger text-warning justify-content-center align-items-center">
                            YOU
                        </div>
                    {% else %}
                        <div class="col-1 d-flex bg-success text-warning justify-content-center align-items-center">
                            {% with top_teams|length as i %}
                                {{forloop.counter|add:i}}
                            {% endwith %}
                        </div>
                    {% endif %}
                        
                        
                        
                    <div class="bg-light col-11">
                        <h3 class="title h3 text-center">{{team.name}}</h3>
                        <div class=" d-flex flex-row px-5">
                            <div class="col-4 text-center">
                                <b>Flag found : </b> {{team.flag_validated}}
                            </div>
                            <div class="col-4 text-center">
                                <b>Last flag found : </b> {{team.last_flag_found}}
                            </div>
                            <div class="col-4 text-center">
                                <b>From : </b> {{team.city}}
                            </div>
                        </div>
                    </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}
    

    

templates/ctf/login.html
{% extends 'container.html' %}
{% block title %}
	Membership | Login | {{post.title}}
{% endblock title %}
{% block content %}
    <form method="POST">
        LOGIN : {{form.as_p}} 
        {% csrf_token %}
        <button>Login</button>
    </form>
{% endblock content %}

templates/ctf/rules.html
{% extends 'container.html' %}

{% block content %}
    <h4 class="text-white">Hello there,</h4>
    <p class="text-white">Here are the <b>RULES</b> of our game</p>
{% endblock content %}
    

templates/ctf/submit-flag.html
{% extends 'container.html' %}

{% block content %}
    <div class="container m-auto">
        <div class="d-flex flex-column align-items-center justify-contents-center h-100 w-100">
            <div class="align-items-center flex-column d-flex w-50 m-auto">
                <h1 class="text-light text-center">Submit a flag</h1>
                <p class="text-light">Submit a flag to get the instruction about the next room or the next flag of the current room</p>
                <form class="w-100" method="post">
                    <div class="mb-3">
                        <label for="flag" class="text-secondary text-center h3">flag</label>
                        <div class="input-group">
                        <input class="form-control" type="text" name="flag" id="flag" placeholder="******************************************************">
                        </div>
                    </div>
                    {% csrf_token %}
                    <button class="btn btn-primary form-control">Submit</button>
                </form>
            </div>

            <div class="w-50">
                {% if team.current_flag %}
                    <div class="bg-light my-5 p-3">
                        <h2 class="title h2">Where to find the flag???</h2>
                        <p>{{ team.current_flag.description }}</p>
                        <p>Value : {{team.current_flag.value}}</p>
                    </div>
                {% endif %}
            </div>   
        </div> 
    </div>
{% endblock content %}